<?php
// Read-only verification of the configuration generated by a clean Composer install.
$root = getenv('SKEEKS_APP_ROOT');
if (!$root) { throw new RuntimeException('Set SKEEKS_APP_ROOT to the clean install directory.'); }
define('ROOT_DIR', $root);
define('YII_ENV', 'dev');
define('YII_DEBUG', true);
require $root.'/vendor/skeeks/cms/bootstrap.php';
$config = new Yiisoft\Config\Config(
    new Yiisoft\Config\ConfigPaths($root, 'config'), null,
    [Yiisoft\Config\Modifier\RecursiveMerge::groups('console', 'web')], null
);
$console = $config->get('console');
$web = $config->get('web');
$checks = [
    'console job component' => ($console['components']['jobs']['class'] ?? null) === skeeks\cms\job\CmsJobComponent::class,
    'web job component' => ($web['components']['jobs']['class'] ?? null) === skeeks\cms\job\CmsJobComponent::class,
    'public worker module' => ($console['modules']['cms-job']['class'] ?? null) === skeeks\cms\job\CmsJobModule::class,
    'explicit migration registration' => in_array('@skeeks/cms/job/migrations', $console['controllerMap']['migrate']['migrationPath'] ?? [], true),
    'only core console lanes' => array_keys($console['components']['jobQueueFactory']['queues'] ?? []) === ['default', 'maintenance'],
    'only core web lanes' => array_keys($web['components']['jobQueueFactory']['queues'] ?? []) === ['default', 'maintenance'],
    'real Composer queue autoload' => class_exists(yii\queue\db\Queue::class),
];
$extended = yii\helpers\ArrayHelper::merge($console, require __DIR__.'/fixtures/consumer-config.php');
$checks['consumer adds lanes without losing core'] = count($extended['components']['jobQueueFactory']['queues']) === 8;
$overridden = yii\helpers\ArrayHelper::merge($extended, [
    'components' => ['jobQueueFactory' => ['queues' => ['hosting' => ['channel' => 'project-hosting']]]],
]);
$checks['project overrides consumer settings'] = $overridden['components']['jobQueueFactory']['queues']['hosting']['channel'] === 'project-hosting'
    && isset($overridden['components']['jobQueueFactory']['queues']['imports']);
$factory = Yii::createObject($console['components']['jobQueueFactory']);
$checks['unregistered consumer lane unavailable'] = !$factory->has('hosting');
foreach ($checks as $message => $ok) {
    if (!$ok) { throw new RuntimeException($message); }
    echo 'PASS '.$message."\n";
}
echo 'OK '.count($checks)." Composer config checks\n";
